const crypto = require("crypto");

const plainText = "Somebody is coding again!"
const secret = 'super-secret-key';
const hash = crypto.createHash("md5").update(plainText).digest("hex");
const hash2 = crypto.createHash("sha1").update(plainText).digest("hex");
const hash3 = crypto.createHash("sha-1").update(plainText).digest("hex");
const hash4 = crypto.createHash("sha224").update(plainText).digest("hex");
const hash5 = crypto.createHash("sha-224").update(plainText).digest("hex");
const hash6 = crypto.createHash("sha256").update(plainText).digest("hex");
const hash7 = crypto.createHash("sha-256").update(plainText).digest("hex");
const hash8 = crypto.createHash("sha384").update(plainText).digest("hex");
const hash9 = crypto.createHash("sha-384").update(plainText).digest("hex");
const hash10 = crypto.createHash("sha512").update(plainText).digest("hex");
const hash11 = crypto.createHash("sha-512").update(plainText).digest("hex");
const hash12 = crypto.createHash("sha3-256").update(plainText).digest("hex");
const hash13 = crypto.createHash("sha3-384").update(plainText).digest("hex");
const hash14 = crypto.createHash("sha3-512").update(plainText).digest("hex");
const hash15 = crypto.createHash("blake2b512").update(plainText).digest("hex");
const hash16 = crypto.createHash("blake2s256").update(plainText).digest("hex");
const hash17 = crypto.createHash("ripemd160").update(plainText).digest("hex");

const hmac1 = crypto.createHmac("md5", secret).update(plainText).digest("hex");
const hmac2 = crypto.createHmac("sha1", secret).update(plainText).digest("hex");
const hmac3 = crypto.createHmac("sha-1", secret).update(plainText).digest("hex");
const hmac4 = crypto.createHmac("sha224", secret).update(plainText).digest("hex");
const hmac5 = crypto.createHmac("sha-224", secret).update(plainText).digest("hex");
const hmac6 = crypto.createHmac("sha256", secret).update(plainText).digest("hex");
const hmac7 = crypto.createHmac("sha-256", secret).update(plainText).digest("hex");
const hmac8 = crypto.createHmac("sha384", secret).update(plainText).digest("hex");
const hmac9 = crypto.createHmac("sha-384", secret).update(plainText).digest("hex");
const hmac10 = crypto.createHmac("sha512", secret).update(plainText).digest("hex");
const hmac11 = crypto.createHmac("sha-512", secret).update(plainText).digest("hex");
const hmac12 = crypto.createHmac("sha3-256", secret).update(plainText).digest("hex");
const hmac13 = crypto.createHmac("sha3-384", secret).update(plainText).digest("hex");
const hmac14 = crypto.createHmac("sha3-512", secret).update(plainText).digest("hex");
const hmac15 = crypto.createHmac("blake2b512", secret).update(plainText).digest("hex");
const hmac16 = crypto.createHmac("blake2s256", secret).update(plainText).digest("hex");
const hmac17 = crypto.createHmac("ripemd160", secret).update(plainText).digest("hex");
    

console.log("-------------------Hashing-------------------");
console.log("Plain text is: "+ plainText + " MD5 Value is: "+ hash);
console.log("Plain text is: "+ plainText + " SHA1 Value is: "+ hash2);
console.log("Plain text is: "+ plainText + " SHA-1 Value is: "+ hash3);
console.log("Plain text is: "+ plainText + " SHA224 Value is: "+ hash4);
console.log("Plain text is: "+ plainText + " SHA-224 Value is: "+ hash5);
console.log("Plain text is: "+ plainText + " SHA256 Value is: "+ hash6);
console.log("Plain text is: "+ plainText + " SHA-256 Value is: "+ hash7);
console.log("Plain text is: "+ plainText + " SHA384 Value is: "+ hash8);
console.log("Plain text is: "+ plainText + " SHA-384 Value is: "+ hash9);
console.log("Plain text is: "+ plainText + " SHA512 Value is: "+ hash10);
console.log("Plain text is: "+ plainText + " SHA-512 Value is: "+ hash11);
console.log("Plain text is: "+ plainText + " SHA3-256 Value is: "+ hash12);
console.log("Plain text is: "+ plainText + " SHA3-384 Value is: "+ hash13);
console.log("Plain text is: "+ plainText + " SHA3-512 Value is: "+ hash14);
console.log("Plain text is: "+ plainText + " BLAKE2B512 Value is: "+ hash15);
console.log("Plain text is: "+ plainText + " BLAKE2S256 Value is: "+ hash16);
console.log("Plain text is: "+ plainText + " RIPEMD160 Value is: "+ hash17);
console.log("-------------------HMAC-------------------");
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " MD5 HMAC Value is: "+ hmac1);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA1 HMAC Value is: "+ hmac2);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA-1 HMAC Value is: "+ hmac3);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA224 HMAC Value is: "+ hmac4);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA-224 HMAC Value is: "+ hmac5);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA256 HMAC Value is: "+ hmac6);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA-256 HMAC Value is: "+ hmac7);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA384 HMAC Value is: "+ hmac8);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA-384 HMAC Value is: "+ hmac9);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA512 HMAC Value is: "+ hmac10);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA-512 HMAC Value is: "+ hmac11);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA3-256 HMAC Value is: "+ hmac12);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA3-384 HMAC Value is: "+ hmac13);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " SHA3-512 HMAC Value is: "+ hmac14);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " BLAKE2B512 HMAC Value is: "+ hmac15);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " BLAKE2S256 HMAC Value is: "+ hmac16);
console.log("Plain text is: "+ plainText + " Secret is: "+ secret + " RIPEMD160 HMAC Value is: "+ hmac17);

